/*
 * This file is generated by jOOQ.
 */
package eu.fasten.analyzer.metadataplugin.db.codegen.tables;


import eu.fasten.analyzer.metadataplugin.db.codegen.Indexes;
import eu.fasten.analyzer.metadataplugin.db.codegen.Keys;
import eu.fasten.analyzer.metadataplugin.db.codegen.Public;
import eu.fasten.analyzer.metadataplugin.db.codegen.tables.records.CallablesRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Callables extends TableImpl<CallablesRecord> {

    private static final long serialVersionUID = 1947267073;

    /**
     * The reference instance of <code>public.callables</code>
     */
    public static final Callables CALLABLES = new Callables();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CallablesRecord> getRecordType() {
        return CallablesRecord.class;
    }

    /**
     * The column <code>public.callables.id</code>.
     */
    public final TableField<CallablesRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("nextval('callables_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.callables.file_id</code>.
     */
    public final TableField<CallablesRecord, Long> FILE_ID = createField(DSL.name("file_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.callables.fasten_uri</code>.
     */
    public final TableField<CallablesRecord, String> FASTEN_URI = createField(DSL.name("fasten_uri"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.callables.created_at</code>.
     */
    public final TableField<CallablesRecord, Timestamp> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.callables.metadata</code>.
     */
    public final TableField<CallablesRecord, JSONB> METADATA = createField(DSL.name("metadata"), org.jooq.impl.SQLDataType.JSONB, this, "");

    /**
     * Create a <code>public.callables</code> table reference
     */
    public Callables() {
        this(DSL.name("callables"), null);
    }

    /**
     * Create an aliased <code>public.callables</code> table reference
     */
    public Callables(String alias) {
        this(DSL.name(alias), CALLABLES);
    }

    /**
     * Create an aliased <code>public.callables</code> table reference
     */
    public Callables(Name alias) {
        this(alias, CALLABLES);
    }

    private Callables(Name alias, Table<CallablesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Callables(Name alias, Table<CallablesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Callables(Table<O> child, ForeignKey<O, CallablesRecord> key) {
        super(child, key, CALLABLES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CALLABLES_PKEY);
    }

    @Override
    public Identity<CallablesRecord, Long> getIdentity() {
        return Keys.IDENTITY_CALLABLES;
    }

    @Override
    public UniqueKey<CallablesRecord> getPrimaryKey() {
        return Keys.CALLABLES_PKEY;
    }

    @Override
    public List<UniqueKey<CallablesRecord>> getKeys() {
        return Arrays.<UniqueKey<CallablesRecord>>asList(Keys.CALLABLES_PKEY);
    }

    @Override
    public List<ForeignKey<CallablesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CallablesRecord, ?>>asList(Keys.CALLABLES__CALLABLES_FILE_ID_FKEY);
    }

    public Files files() {
        return new Files(this, Keys.CALLABLES__CALLABLES_FILE_ID_FKEY);
    }

    @Override
    public Callables as(String alias) {
        return new Callables(DSL.name(alias), this);
    }

    @Override
    public Callables as(Name alias) {
        return new Callables(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Callables rename(String name) {
        return new Callables(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Callables rename(Name name) {
        return new Callables(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, Timestamp, JSONB> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
