/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen;


import eu.fasten.core.data.metadatadb.codegen.udt.CallSite;
import eu.fasten.core.data.metadatadb.codegen.udt.Receiver;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all UDTs in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UDTs {

    /**
     * The type <code>public.call_site</code>
     */
    public static CallSite CALL_SITE = eu.fasten.core.data.metadatadb.codegen.udt.CallSite.CALL_SITE;

    /**
     * The type <code>public.receiver</code>
     */
    public static Receiver RECEIVER = eu.fasten.core.data.metadatadb.codegen.udt.Receiver.RECEIVER;
}
