/*
 * This file is generated by jOOQ.
 */
package eu.fasten.analyzer.metadataplugin.db.codegen.tables.records;


import eu.fasten.analyzer.metadataplugin.db.codegen.tables.Packages;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PackagesRecord extends UpdatableRecordImpl<PackagesRecord> implements Record5<Long, String, String, String, Timestamp> {

    private static final long serialVersionUID = -1297367866;

    /**
     * Setter for <code>public.packages.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.packages.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.packages.package_name</code>.
     */
    public void setPackageName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.packages.package_name</code>.
     */
    public String getPackageName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.packages.project_name</code>.
     */
    public void setProjectName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.packages.project_name</code>.
     */
    public String getProjectName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.packages.repository</code>.
     */
    public void setRepository(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.packages.repository</code>.
     */
    public String getRepository() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.packages.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.packages.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Packages.PACKAGES.ID;
    }

    @Override
    public Field<String> field2() {
        return Packages.PACKAGES.PACKAGE_NAME;
    }

    @Override
    public Field<String> field3() {
        return Packages.PACKAGES.PROJECT_NAME;
    }

    @Override
    public Field<String> field4() {
        return Packages.PACKAGES.REPOSITORY;
    }

    @Override
    public Field<Timestamp> field5() {
        return Packages.PACKAGES.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPackageName();
    }

    @Override
    public String component3() {
        return getProjectName();
    }

    @Override
    public String component4() {
        return getRepository();
    }

    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPackageName();
    }

    @Override
    public String value3() {
        return getProjectName();
    }

    @Override
    public String value4() {
        return getRepository();
    }

    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    @Override
    public PackagesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PackagesRecord value2(String value) {
        setPackageName(value);
        return this;
    }

    @Override
    public PackagesRecord value3(String value) {
        setProjectName(value);
        return this;
    }

    @Override
    public PackagesRecord value4(String value) {
        setRepository(value);
        return this;
    }

    @Override
    public PackagesRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public PackagesRecord values(Long value1, String value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PackagesRecord
     */
    public PackagesRecord() {
        super(Packages.PACKAGES);
    }

    /**
     * Create a detached, initialised PackagesRecord
     */
    public PackagesRecord(Long id, String packageName, String projectName, String repository, Timestamp createdAt) {
        super(Packages.PACKAGES);

        set(0, id);
        set(1, packageName);
        set(2, projectName);
        set(3, repository);
        set(4, createdAt);
    }
}
