/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.udt.records;


import eu.fasten.core.data.metadatadb.codegen.enums.ReceiverType;
import eu.fasten.core.data.metadatadb.codegen.udt.Receiver;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UDTRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReceiverRecord extends UDTRecordImpl<ReceiverRecord> implements Record3<Integer, ReceiverType, Long> {

    private static final long serialVersionUID = 731516747;

    /**
     * Setter for <code>public.receiver.line</code>.
     */
    public void setLine(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.receiver.line</code>.
     */
    public Integer getLine() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.receiver.receiver_type</code>.
     */
    public void setReceiverType(ReceiverType value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.receiver.receiver_type</code>.
     */
    public ReceiverType getReceiverType() {
        return (ReceiverType) get(1);
    }

    /**
     * Setter for <code>public.receiver.namespace_id</code>.
     */
    public void setNamespaceId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.receiver.namespace_id</code>.
     */
    public Long getNamespaceId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, ReceiverType, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, ReceiverType, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Receiver.LINE;
    }

    @Override
    public Field<ReceiverType> field2() {
        return Receiver.RECEIVER_TYPE;
    }

    @Override
    public Field<Long> field3() {
        return Receiver.NAMESPACE_ID;
    }

    @Override
    public Integer component1() {
        return getLine();
    }

    @Override
    public ReceiverType component2() {
        return getReceiverType();
    }

    @Override
    public Long component3() {
        return getNamespaceId();
    }

    @Override
    public Integer value1() {
        return getLine();
    }

    @Override
    public ReceiverType value2() {
        return getReceiverType();
    }

    @Override
    public Long value3() {
        return getNamespaceId();
    }

    @Override
    public ReceiverRecord value1(Integer value) {
        setLine(value);
        return this;
    }

    @Override
    public ReceiverRecord value2(ReceiverType value) {
        setReceiverType(value);
        return this;
    }

    @Override
    public ReceiverRecord value3(Long value) {
        setNamespaceId(value);
        return this;
    }

    @Override
    public ReceiverRecord values(Integer value1, ReceiverType value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReceiverRecord
     */
    public ReceiverRecord() {
        super(Receiver.RECEIVER);
    }

    /**
     * Create a detached, initialised ReceiverRecord
     */
    public ReceiverRecord(Integer line, ReceiverType receiverType, Long namespaceId) {
        super(Receiver.RECEIVER);

        set(0, line);
        set(1, receiverType);
        set(2, namespaceId);
    }
}
