/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables;


import eu.fasten.core.data.metadatadb.codegen.Indexes;
import eu.fasten.core.data.metadatadb.codegen.Keys;
import eu.fasten.core.data.metadatadb.codegen.Public;
import eu.fasten.core.data.metadatadb.codegen.tables.records.IngestedArtifactsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IngestedArtifacts extends TableImpl<IngestedArtifactsRecord> {

    private static final long serialVersionUID = -1881456673;

    /**
     * The reference instance of <code>public.ingested_artifacts</code>
     */
    public static final IngestedArtifacts INGESTED_ARTIFACTS = new IngestedArtifacts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IngestedArtifactsRecord> getRecordType() {
        return IngestedArtifactsRecord.class;
    }

    /**
     * The column <code>public.ingested_artifacts.id</code>.
     */
    public final TableField<IngestedArtifactsRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('ingested_artifacts_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.ingested_artifacts.package_name</code>.
     */
    public final TableField<IngestedArtifactsRecord, String> PACKAGE_NAME = createField(DSL.name("package_name"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.ingested_artifacts.version</code>.
     */
    public final TableField<IngestedArtifactsRecord, String> VERSION = createField(DSL.name("version"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.ingested_artifacts.timestamp</code>.
     */
    public final TableField<IngestedArtifactsRecord, Timestamp> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.ingested_artifacts</code> table reference
     */
    public IngestedArtifacts() {
        this(DSL.name("ingested_artifacts"), null);
    }

    /**
     * Create an aliased <code>public.ingested_artifacts</code> table reference
     */
    public IngestedArtifacts(String alias) {
        this(DSL.name(alias), INGESTED_ARTIFACTS);
    }

    /**
     * Create an aliased <code>public.ingested_artifacts</code> table reference
     */
    public IngestedArtifacts(Name alias) {
        this(alias, INGESTED_ARTIFACTS);
    }

    private IngestedArtifacts(Name alias, Table<IngestedArtifactsRecord> aliased) {
        this(alias, aliased, null);
    }

    private IngestedArtifacts(Name alias, Table<IngestedArtifactsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> IngestedArtifacts(Table<O> child, ForeignKey<O, IngestedArtifactsRecord> key) {
        super(child, key, INGESTED_ARTIFACTS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INGESTED_ARTIFACTS_PKEY, Indexes.UNIQUE_INGESTED_ARTIFACTS);
    }

    @Override
    public Identity<IngestedArtifactsRecord, Long> getIdentity() {
        return Keys.IDENTITY_INGESTED_ARTIFACTS;
    }

    @Override
    public UniqueKey<IngestedArtifactsRecord> getPrimaryKey() {
        return Keys.INGESTED_ARTIFACTS_PKEY;
    }

    @Override
    public List<UniqueKey<IngestedArtifactsRecord>> getKeys() {
        return Arrays.<UniqueKey<IngestedArtifactsRecord>>asList(Keys.INGESTED_ARTIFACTS_PKEY, Keys.UNIQUE_INGESTED_ARTIFACTS);
    }

    @Override
    public IngestedArtifacts as(String alias) {
        return new IngestedArtifacts(DSL.name(alias), this);
    }

    @Override
    public IngestedArtifacts as(Name alias) {
        return new IngestedArtifacts(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IngestedArtifacts rename(String name) {
        return new IngestedArtifacts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IngestedArtifacts rename(Name name) {
        return new IngestedArtifacts(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
