/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables;


import eu.fasten.core.data.metadatadb.codegen.Keys;
import eu.fasten.core.data.metadatadb.codegen.Public;
import eu.fasten.core.data.metadatadb.codegen.tables.records.VulnerabilitiesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vulnerabilities extends TableImpl<VulnerabilitiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vulnerabilities</code>
     */
    public static final Vulnerabilities VULNERABILITIES = new Vulnerabilities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VulnerabilitiesRecord> getRecordType() {
        return VulnerabilitiesRecord.class;
    }

    /**
     * The column <code>public.vulnerabilities.id</code>.
     */
    public final TableField<VulnerabilitiesRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.vulnerabilities.statement</code>.
     */
    public final TableField<VulnerabilitiesRecord, JSONB> STATEMENT = createField(DSL.name("statement"), SQLDataType.JSONB, this, "");

    private Vulnerabilities(Name alias, Table<VulnerabilitiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Vulnerabilities(Name alias, Table<VulnerabilitiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.vulnerabilities</code> table reference
     */
    public Vulnerabilities(String alias) {
        this(DSL.name(alias), VULNERABILITIES);
    }

    /**
     * Create an aliased <code>public.vulnerabilities</code> table reference
     */
    public Vulnerabilities(Name alias) {
        this(alias, VULNERABILITIES);
    }

    /**
     * Create a <code>public.vulnerabilities</code> table reference
     */
    public Vulnerabilities() {
        this(DSL.name("vulnerabilities"), null);
    }

    public <O extends Record> Vulnerabilities(Table<O> child, ForeignKey<O, VulnerabilitiesRecord> key) {
        super(child, key, VULNERABILITIES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<VulnerabilitiesRecord> getPrimaryKey() {
        return Keys.VULNERABILITIES_PKEY;
    }

    @Override
    public List<UniqueKey<VulnerabilitiesRecord>> getKeys() {
        return Arrays.<UniqueKey<VulnerabilitiesRecord>>asList(Keys.VULNERABILITIES_PKEY);
    }

    @Override
    public Vulnerabilities as(String alias) {
        return new Vulnerabilities(DSL.name(alias), this);
    }

    @Override
    public Vulnerabilities as(Name alias) {
        return new Vulnerabilities(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Vulnerabilities rename(String name) {
        return new Vulnerabilities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Vulnerabilities rename(Name name) {
        return new Vulnerabilities(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, JSONB> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
