/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables;


import eu.fasten.core.data.metadatadb.codegen.Indexes;
import eu.fasten.core.data.metadatadb.codegen.Keys;
import eu.fasten.core.data.metadatadb.codegen.Public;
import eu.fasten.core.data.metadatadb.codegen.tables.records.VulnerabilitiesXPackageVersionsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.15"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VulnerabilitiesXPackageVersions extends TableImpl<VulnerabilitiesXPackageVersionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vulnerabilities_x_package_versions</code>
     */
    public static final VulnerabilitiesXPackageVersions VULNERABILITIES_X_PACKAGE_VERSIONS = new VulnerabilitiesXPackageVersions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VulnerabilitiesXPackageVersionsRecord> getRecordType() {
        return VulnerabilitiesXPackageVersionsRecord.class;
    }

    /**
     * The column <code>public.vulnerabilities_x_package_versions.vulnerability_id</code>.
     */
    public final TableField<VulnerabilitiesXPackageVersionsRecord, Long> VULNERABILITY_ID = createField(DSL.name("vulnerability_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vulnerabilities_x_package_versions.package_version_id</code>.
     */
    public final TableField<VulnerabilitiesXPackageVersionsRecord, Long> PACKAGE_VERSION_ID = createField(DSL.name("package_version_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private VulnerabilitiesXPackageVersions(Name alias, Table<VulnerabilitiesXPackageVersionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private VulnerabilitiesXPackageVersions(Name alias, Table<VulnerabilitiesXPackageVersionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.vulnerabilities_x_package_versions</code> table reference
     */
    public VulnerabilitiesXPackageVersions(String alias) {
        this(DSL.name(alias), VULNERABILITIES_X_PACKAGE_VERSIONS);
    }

    /**
     * Create an aliased <code>public.vulnerabilities_x_package_versions</code> table reference
     */
    public VulnerabilitiesXPackageVersions(Name alias) {
        this(alias, VULNERABILITIES_X_PACKAGE_VERSIONS);
    }

    /**
     * Create a <code>public.vulnerabilities_x_package_versions</code> table reference
     */
    public VulnerabilitiesXPackageVersions() {
        this(DSL.name("vulnerabilities_x_package_versions"), null);
    }

    public <O extends Record> VulnerabilitiesXPackageVersions(Table<O> child, ForeignKey<O, VulnerabilitiesXPackageVersionsRecord> key) {
        super(child, key, VULNERABILITIES_X_PACKAGE_VERSIONS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.VULNERABILITIES_X_PACKAGE_VERSIONS_PACKAGE_VERSION_ID, Indexes.VULNERABILITIES_X_PACKAGE_VERSIONS_VULNERABILITY_ID);
    }

    @Override
    public List<ForeignKey<VulnerabilitiesXPackageVersionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VulnerabilitiesXPackageVersionsRecord, ?>>asList(Keys.VULNERABILITIES_X_PACKAGE_VERSIONS__VULNERABILITIES_X_PACKAGE_VERSIONS_VULNERABILITY_ID_FKEY, Keys.VULNERABILITIES_X_PACKAGE_VERSIONS__VULNERABILITIES_X_PACKAGE_VERSIONS_PACKAGE_VERSION_ID_FKEY);
    }

    private transient Vulnerabilities _vulnerabilities;
    private transient PackageVersions _packageVersions;

    public Vulnerabilities vulnerabilities() {
        if (_vulnerabilities == null)
            _vulnerabilities = new Vulnerabilities(this, Keys.VULNERABILITIES_X_PACKAGE_VERSIONS__VULNERABILITIES_X_PACKAGE_VERSIONS_VULNERABILITY_ID_FKEY);

        return _vulnerabilities;
    }

    public PackageVersions packageVersions() {
        if (_packageVersions == null)
            _packageVersions = new PackageVersions(this, Keys.VULNERABILITIES_X_PACKAGE_VERSIONS__VULNERABILITIES_X_PACKAGE_VERSIONS_PACKAGE_VERSION_ID_FKEY);

        return _packageVersions;
    }

    @Override
    public VulnerabilitiesXPackageVersions as(String alias) {
        return new VulnerabilitiesXPackageVersions(DSL.name(alias), this);
    }

    @Override
    public VulnerabilitiesXPackageVersions as(Name alias) {
        return new VulnerabilitiesXPackageVersions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VulnerabilitiesXPackageVersions rename(String name) {
        return new VulnerabilitiesXPackageVersions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VulnerabilitiesXPackageVersions rename(Name name) {
        return new VulnerabilitiesXPackageVersions(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
