/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables.records;


import eu.fasten.core.data.metadatadb.codegen.tables.ArtifactStates;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArtifactStatesRecord extends UpdatableRecordImpl<ArtifactStatesRecord> implements Record4<Long, String, String, Boolean> {

    private static final long serialVersionUID = 25891503;

    /**
     * Setter for <code>public.artifact_states.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.artifact_states.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.artifact_states.package_name</code>.
     */
    public void setPackageName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.artifact_states.package_name</code>.
     */
    public String getPackageName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.artifact_states.version</code>.
     */
    public void setVersion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.artifact_states.version</code>.
     */
    public String getVersion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.artifact_states.is_ingested</code>.
     */
    public void setIsIngested(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.artifact_states.is_ingested</code>.
     */
    public Boolean getIsIngested() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ArtifactStates.ARTIFACT_STATES.ID;
    }

    @Override
    public Field<String> field2() {
        return ArtifactStates.ARTIFACT_STATES.PACKAGE_NAME;
    }

    @Override
    public Field<String> field3() {
        return ArtifactStates.ARTIFACT_STATES.VERSION;
    }

    @Override
    public Field<Boolean> field4() {
        return ArtifactStates.ARTIFACT_STATES.IS_INGESTED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPackageName();
    }

    @Override
    public String component3() {
        return getVersion();
    }

    @Override
    public Boolean component4() {
        return getIsIngested();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPackageName();
    }

    @Override
    public String value3() {
        return getVersion();
    }

    @Override
    public Boolean value4() {
        return getIsIngested();
    }

    @Override
    public ArtifactStatesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ArtifactStatesRecord value2(String value) {
        setPackageName(value);
        return this;
    }

    @Override
    public ArtifactStatesRecord value3(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public ArtifactStatesRecord value4(Boolean value) {
        setIsIngested(value);
        return this;
    }

    @Override
    public ArtifactStatesRecord values(Long value1, String value2, String value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArtifactStatesRecord
     */
    public ArtifactStatesRecord() {
        super(ArtifactStates.ARTIFACT_STATES);
    }

    /**
     * Create a detached, initialised ArtifactStatesRecord
     */
    public ArtifactStatesRecord(Long id, String packageName, String version, Boolean isIngested) {
        super(ArtifactStates.ARTIFACT_STATES);

        set(0, id);
        set(1, packageName);
        set(2, version);
        set(3, isIngested);
    }
}
