/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables.records;


import eu.fasten.core.data.metadatadb.codegen.tables.ArtifactRepositories;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArtifactRepositoriesRecord extends UpdatableRecordImpl<ArtifactRepositoriesRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1490667605;

    /**
     * Setter for <code>public.artifact_repositories.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.artifact_repositories.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.artifact_repositories.repository_base_url</code>.
     */
    public void setRepositoryBaseUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.artifact_repositories.repository_base_url</code>.
     */
    public String getRepositoryBaseUrl() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ArtifactRepositories.ARTIFACT_REPOSITORIES.ID;
    }

    @Override
    public Field<String> field2() {
        return ArtifactRepositories.ARTIFACT_REPOSITORIES.REPOSITORY_BASE_URL;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRepositoryBaseUrl();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRepositoryBaseUrl();
    }

    @Override
    public ArtifactRepositoriesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ArtifactRepositoriesRecord value2(String value) {
        setRepositoryBaseUrl(value);
        return this;
    }

    @Override
    public ArtifactRepositoriesRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArtifactRepositoriesRecord
     */
    public ArtifactRepositoriesRecord() {
        super(ArtifactRepositories.ARTIFACT_REPOSITORIES);
    }

    /**
     * Create a detached, initialised ArtifactRepositoriesRecord
     */
    public ArtifactRepositoriesRecord(Long id, String repositoryBaseUrl) {
        super(ArtifactRepositories.ARTIFACT_REPOSITORIES);

        set(0, id);
        set(1, repositoryBaseUrl);
    }
}
