/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables.records;


import eu.fasten.core.data.metadatadb.codegen.tables.Callables;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CallablesRecord extends UpdatableRecordImpl<CallablesRecord> implements Record6<Long, Long, String, Boolean, Timestamp, JSONB> {

    private static final long serialVersionUID = 2046808601;

    /**
     * Setter for <code>public.callables.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.callables.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.callables.module_id</code>.
     */
    public void setModuleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.callables.module_id</code>.
     */
    public Long getModuleId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.callables.fasten_uri</code>.
     */
    public void setFastenUri(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.callables.fasten_uri</code>.
     */
    public String getFastenUri() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.callables.is_resolved_call</code>.
     */
    public void setIsResolvedCall(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.callables.is_resolved_call</code>.
     */
    public Boolean getIsResolvedCall() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.callables.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.callables.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.callables.metadata</code>.
     */
    public void setMetadata(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.callables.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, Boolean, Timestamp, JSONB> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, String, Boolean, Timestamp, JSONB> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Callables.CALLABLES.ID;
    }

    @Override
    public Field<Long> field2() {
        return Callables.CALLABLES.MODULE_ID;
    }

    @Override
    public Field<String> field3() {
        return Callables.CALLABLES.FASTEN_URI;
    }

    @Override
    public Field<Boolean> field4() {
        return Callables.CALLABLES.IS_RESOLVED_CALL;
    }

    @Override
    public Field<Timestamp> field5() {
        return Callables.CALLABLES.CREATED_AT;
    }

    @Override
    public Field<JSONB> field6() {
        return Callables.CALLABLES.METADATA;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getModuleId();
    }

    @Override
    public String component3() {
        return getFastenUri();
    }

    @Override
    public Boolean component4() {
        return getIsResolvedCall();
    }

    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    @Override
    public JSONB component6() {
        return getMetadata();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getModuleId();
    }

    @Override
    public String value3() {
        return getFastenUri();
    }

    @Override
    public Boolean value4() {
        return getIsResolvedCall();
    }

    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    @Override
    public JSONB value6() {
        return getMetadata();
    }

    @Override
    public CallablesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CallablesRecord value2(Long value) {
        setModuleId(value);
        return this;
    }

    @Override
    public CallablesRecord value3(String value) {
        setFastenUri(value);
        return this;
    }

    @Override
    public CallablesRecord value4(Boolean value) {
        setIsResolvedCall(value);
        return this;
    }

    @Override
    public CallablesRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CallablesRecord value6(JSONB value) {
        setMetadata(value);
        return this;
    }

    @Override
    public CallablesRecord values(Long value1, Long value2, String value3, Boolean value4, Timestamp value5, JSONB value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CallablesRecord
     */
    public CallablesRecord() {
        super(Callables.CALLABLES);
    }

    /**
     * Create a detached, initialised CallablesRecord
     */
    public CallablesRecord(Long id, Long moduleId, String fastenUri, Boolean isResolvedCall, Timestamp createdAt, JSONB metadata) {
        super(Callables.CALLABLES);

        set(0, id);
        set(1, moduleId);
        set(2, fastenUri);
        set(3, isResolvedCall);
        set(4, createdAt);
        set(5, metadata);
    }
}
