/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables.records;


import eu.fasten.core.data.metadatadb.codegen.enums.CallType;
import eu.fasten.core.data.metadatadb.codegen.tables.CallSites;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CallSitesRecord extends TableRecordImpl<CallSitesRecord> implements Record6<Long, Long, Integer, CallType, Long[], JSONB> {

    private static final long serialVersionUID = 2137342999;

    /**
     * Setter for <code>public.call_sites.source_id</code>.
     */
    public void setSourceId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.call_sites.source_id</code>.
     */
    public Long getSourceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.call_sites.target_id</code>.
     */
    public void setTargetId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.call_sites.target_id</code>.
     */
    public Long getTargetId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.call_sites.line</code>.
     */
    public void setLine(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.call_sites.line</code>.
     */
    public Integer getLine() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.call_sites.call_type</code>.
     */
    public void setCallType(CallType value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.call_sites.call_type</code>.
     */
    public CallType getCallType() {
        return (CallType) get(3);
    }

    /**
     * Setter for <code>public.call_sites.receiver_type_ids</code>.
     */
    public void setReceiverTypeIds(Long... value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.call_sites.receiver_type_ids</code>.
     */
    public Long[] getReceiverTypeIds() {
        return (Long[]) get(4);
    }

    /**
     * Setter for <code>public.call_sites.metadata</code>.
     */
    public void setMetadata(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.call_sites.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Integer, CallType, Long[], JSONB> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Integer, CallType, Long[], JSONB> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CallSites.CALL_SITES.SOURCE_ID;
    }

    @Override
    public Field<Long> field2() {
        return CallSites.CALL_SITES.TARGET_ID;
    }

    @Override
    public Field<Integer> field3() {
        return CallSites.CALL_SITES.LINE;
    }

    @Override
    public Field<CallType> field4() {
        return CallSites.CALL_SITES.CALL_TYPE;
    }

    @Override
    public Field<Long[]> field5() {
        return CallSites.CALL_SITES.RECEIVER_TYPE_IDS;
    }

    @Override
    public Field<JSONB> field6() {
        return CallSites.CALL_SITES.METADATA;
    }

    @Override
    public Long component1() {
        return getSourceId();
    }

    @Override
    public Long component2() {
        return getTargetId();
    }

    @Override
    public Integer component3() {
        return getLine();
    }

    @Override
    public CallType component4() {
        return getCallType();
    }

    @Override
    public Long[] component5() {
        return getReceiverTypeIds();
    }

    @Override
    public JSONB component6() {
        return getMetadata();
    }

    @Override
    public Long value1() {
        return getSourceId();
    }

    @Override
    public Long value2() {
        return getTargetId();
    }

    @Override
    public Integer value3() {
        return getLine();
    }

    @Override
    public CallType value4() {
        return getCallType();
    }

    @Override
    public Long[] value5() {
        return getReceiverTypeIds();
    }

    @Override
    public JSONB value6() {
        return getMetadata();
    }

    @Override
    public CallSitesRecord value1(Long value) {
        setSourceId(value);
        return this;
    }

    @Override
    public CallSitesRecord value2(Long value) {
        setTargetId(value);
        return this;
    }

    @Override
    public CallSitesRecord value3(Integer value) {
        setLine(value);
        return this;
    }

    @Override
    public CallSitesRecord value4(CallType value) {
        setCallType(value);
        return this;
    }

    @Override
    public CallSitesRecord value5(Long... value) {
        setReceiverTypeIds(value);
        return this;
    }

    @Override
    public CallSitesRecord value6(JSONB value) {
        setMetadata(value);
        return this;
    }

    @Override
    public CallSitesRecord values(Long value1, Long value2, Integer value3, CallType value4, Long[] value5, JSONB value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CallSitesRecord
     */
    public CallSitesRecord() {
        super(CallSites.CALL_SITES);
    }

    /**
     * Create a detached, initialised CallSitesRecord
     */
    public CallSitesRecord(Long sourceId, Long targetId, Integer line, CallType callType, Long[] receiverTypeIds, JSONB metadata) {
        super(CallSites.CALL_SITES);

        set(0, sourceId);
        set(1, targetId);
        set(2, line);
        set(3, callType);
        set(4, receiverTypeIds);
        set(5, metadata);
    }
}
