/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables.records;


import eu.fasten.core.data.metadatadb.codegen.enums.Access;
import eu.fasten.core.data.metadatadb.codegen.enums.CallableType;
import eu.fasten.core.data.metadatadb.codegen.tables.Callables;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CallablesRecord extends UpdatableRecordImpl<CallablesRecord> implements Record10<Long, Long, String, Boolean, Integer, Integer, CallableType, Boolean, Access, JSONB> {

    private static final long serialVersionUID = -1182044565;

    /**
     * Setter for <code>public.callables.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.callables.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.callables.module_id</code>.
     */
    public void setModuleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.callables.module_id</code>.
     */
    public Long getModuleId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.callables.fasten_uri</code>.
     */
    public void setFastenUri(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.callables.fasten_uri</code>.
     */
    public String getFastenUri() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.callables.is_internal_call</code>.
     */
    public void setIsInternalCall(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.callables.is_internal_call</code>.
     */
    public Boolean getIsInternalCall() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.callables.line_start</code>.
     */
    public void setLineStart(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.callables.line_start</code>.
     */
    public Integer getLineStart() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.callables.line_end</code>.
     */
    public void setLineEnd(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.callables.line_end</code>.
     */
    public Integer getLineEnd() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.callables.type</code>.
     */
    public void setType(CallableType value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.callables.type</code>.
     */
    public CallableType getType() {
        return (CallableType) get(6);
    }

    /**
     * Setter for <code>public.callables.defined</code>.
     */
    public void setDefined(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.callables.defined</code>.
     */
    public Boolean getDefined() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.callables.access</code>.
     */
    public void setAccess(Access value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.callables.access</code>.
     */
    public Access getAccess() {
        return (Access) get(8);
    }

    /**
     * Setter for <code>public.callables.metadata</code>.
     */
    public void setMetadata(JSONB value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.callables.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, String, Boolean, Integer, Integer, CallableType, Boolean, Access, JSONB> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, String, Boolean, Integer, Integer, CallableType, Boolean, Access, JSONB> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Callables.CALLABLES.ID;
    }

    @Override
    public Field<Long> field2() {
        return Callables.CALLABLES.MODULE_ID;
    }

    @Override
    public Field<String> field3() {
        return Callables.CALLABLES.FASTEN_URI;
    }

    @Override
    public Field<Boolean> field4() {
        return Callables.CALLABLES.IS_INTERNAL_CALL;
    }

    @Override
    public Field<Integer> field5() {
        return Callables.CALLABLES.LINE_START;
    }

    @Override
    public Field<Integer> field6() {
        return Callables.CALLABLES.LINE_END;
    }

    @Override
    public Field<CallableType> field7() {
        return Callables.CALLABLES.TYPE;
    }

    @Override
    public Field<Boolean> field8() {
        return Callables.CALLABLES.DEFINED;
    }

    @Override
    public Field<Access> field9() {
        return Callables.CALLABLES.ACCESS;
    }

    @Override
    public Field<JSONB> field10() {
        return Callables.CALLABLES.METADATA;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getModuleId();
    }

    @Override
    public String component3() {
        return getFastenUri();
    }

    @Override
    public Boolean component4() {
        return getIsInternalCall();
    }

    @Override
    public Integer component5() {
        return getLineStart();
    }

    @Override
    public Integer component6() {
        return getLineEnd();
    }

    @Override
    public CallableType component7() {
        return getType();
    }

    @Override
    public Boolean component8() {
        return getDefined();
    }

    @Override
    public Access component9() {
        return getAccess();
    }

    @Override
    public JSONB component10() {
        return getMetadata();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getModuleId();
    }

    @Override
    public String value3() {
        return getFastenUri();
    }

    @Override
    public Boolean value4() {
        return getIsInternalCall();
    }

    @Override
    public Integer value5() {
        return getLineStart();
    }

    @Override
    public Integer value6() {
        return getLineEnd();
    }

    @Override
    public CallableType value7() {
        return getType();
    }

    @Override
    public Boolean value8() {
        return getDefined();
    }

    @Override
    public Access value9() {
        return getAccess();
    }

    @Override
    public JSONB value10() {
        return getMetadata();
    }

    @Override
    public CallablesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CallablesRecord value2(Long value) {
        setModuleId(value);
        return this;
    }

    @Override
    public CallablesRecord value3(String value) {
        setFastenUri(value);
        return this;
    }

    @Override
    public CallablesRecord value4(Boolean value) {
        setIsInternalCall(value);
        return this;
    }

    @Override
    public CallablesRecord value5(Integer value) {
        setLineStart(value);
        return this;
    }

    @Override
    public CallablesRecord value6(Integer value) {
        setLineEnd(value);
        return this;
    }

    @Override
    public CallablesRecord value7(CallableType value) {
        setType(value);
        return this;
    }

    @Override
    public CallablesRecord value8(Boolean value) {
        setDefined(value);
        return this;
    }

    @Override
    public CallablesRecord value9(Access value) {
        setAccess(value);
        return this;
    }

    @Override
    public CallablesRecord value10(JSONB value) {
        setMetadata(value);
        return this;
    }

    @Override
    public CallablesRecord values(Long value1, Long value2, String value3, Boolean value4, Integer value5, Integer value6, CallableType value7, Boolean value8, Access value9, JSONB value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CallablesRecord
     */
    public CallablesRecord() {
        super(Callables.CALLABLES);
    }

    /**
     * Create a detached, initialised CallablesRecord
     */
    public CallablesRecord(Long id, Long moduleId, String fastenUri, Boolean isInternalCall, Integer lineStart, Integer lineEnd, CallableType type, Boolean defined, Access access, JSONB metadata) {
        super(Callables.CALLABLES);

        set(0, id);
        set(1, moduleId);
        set(2, fastenUri);
        set(3, isInternalCall);
        set(4, lineStart);
        set(5, lineEnd);
        set(6, type);
        set(7, defined);
        set(8, access);
        set(9, metadata);
    }
}
