/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables.records;


import eu.fasten.core.data.metadatadb.codegen.tables.Dependencies;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DependenciesRecord extends TableRecordImpl<DependenciesRecord> implements Record4<Long, Long, String[], JSONB> {

    private static final long serialVersionUID = -1508589592;

    /**
     * Setter for <code>public.dependencies.package_version_id</code>.
     */
    public void setPackageVersionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.dependencies.package_version_id</code>.
     */
    public Long getPackageVersionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.dependencies.dependency_id</code>.
     */
    public void setDependencyId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.dependencies.dependency_id</code>.
     */
    public Long getDependencyId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.dependencies.version_range</code>.
     */
    public void setVersionRange(String... value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.dependencies.version_range</code>.
     */
    public String[] getVersionRange() {
        return (String[]) get(2);
    }

    /**
     * Setter for <code>public.dependencies.metadata</code>.
     */
    public void setMetadata(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.dependencies.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, String[], JSONB> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, String[], JSONB> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Dependencies.DEPENDENCIES.PACKAGE_VERSION_ID;
    }

    @Override
    public Field<Long> field2() {
        return Dependencies.DEPENDENCIES.DEPENDENCY_ID;
    }

    @Override
    public Field<String[]> field3() {
        return Dependencies.DEPENDENCIES.VERSION_RANGE;
    }

    @Override
    public Field<JSONB> field4() {
        return Dependencies.DEPENDENCIES.METADATA;
    }

    @Override
    public Long component1() {
        return getPackageVersionId();
    }

    @Override
    public Long component2() {
        return getDependencyId();
    }

    @Override
    public String[] component3() {
        return getVersionRange();
    }

    @Override
    public JSONB component4() {
        return getMetadata();
    }

    @Override
    public Long value1() {
        return getPackageVersionId();
    }

    @Override
    public Long value2() {
        return getDependencyId();
    }

    @Override
    public String[] value3() {
        return getVersionRange();
    }

    @Override
    public JSONB value4() {
        return getMetadata();
    }

    @Override
    public DependenciesRecord value1(Long value) {
        setPackageVersionId(value);
        return this;
    }

    @Override
    public DependenciesRecord value2(Long value) {
        setDependencyId(value);
        return this;
    }

    @Override
    public DependenciesRecord value3(String... value) {
        setVersionRange(value);
        return this;
    }

    @Override
    public DependenciesRecord value4(JSONB value) {
        setMetadata(value);
        return this;
    }

    @Override
    public DependenciesRecord values(Long value1, Long value2, String[] value3, JSONB value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DependenciesRecord
     */
    public DependenciesRecord() {
        super(Dependencies.DEPENDENCIES);
    }

    /**
     * Create a detached, initialised DependenciesRecord
     */
    public DependenciesRecord(Long packageVersionId, Long dependencyId, String[] versionRange, JSONB metadata) {
        super(Dependencies.DEPENDENCIES);

        set(0, packageVersionId);
        set(1, dependencyId);
        set(2, versionRange);
        set(3, metadata);
    }
}
