/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables.records;


import eu.fasten.core.data.metadatadb.codegen.tables.Modules;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModulesRecord extends UpdatableRecordImpl<ModulesRecord> implements Record5<Long, Long, Long, Timestamp, JSONB> {

    private static final long serialVersionUID = -2001184282;

    /**
     * Setter for <code>public.modules.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.modules.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.modules.package_version_id</code>.
     */
    public void setPackageVersionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.modules.package_version_id</code>.
     */
    public Long getPackageVersionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.modules.namespace_id</code>.
     */
    public void setNamespaceId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.modules.namespace_id</code>.
     */
    public Long getNamespaceId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.modules.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.modules.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.modules.metadata</code>.
     */
    public void setMetadata(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.modules.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, Timestamp, JSONB> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, Timestamp, JSONB> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Modules.MODULES.ID;
    }

    @Override
    public Field<Long> field2() {
        return Modules.MODULES.PACKAGE_VERSION_ID;
    }

    @Override
    public Field<Long> field3() {
        return Modules.MODULES.NAMESPACE_ID;
    }

    @Override
    public Field<Timestamp> field4() {
        return Modules.MODULES.CREATED_AT;
    }

    @Override
    public Field<JSONB> field5() {
        return Modules.MODULES.METADATA;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getPackageVersionId();
    }

    @Override
    public Long component3() {
        return getNamespaceId();
    }

    @Override
    public Timestamp component4() {
        return getCreatedAt();
    }

    @Override
    public JSONB component5() {
        return getMetadata();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getPackageVersionId();
    }

    @Override
    public Long value3() {
        return getNamespaceId();
    }

    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    @Override
    public JSONB value5() {
        return getMetadata();
    }

    @Override
    public ModulesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ModulesRecord value2(Long value) {
        setPackageVersionId(value);
        return this;
    }

    @Override
    public ModulesRecord value3(Long value) {
        setNamespaceId(value);
        return this;
    }

    @Override
    public ModulesRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ModulesRecord value5(JSONB value) {
        setMetadata(value);
        return this;
    }

    @Override
    public ModulesRecord values(Long value1, Long value2, Long value3, Timestamp value4, JSONB value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModulesRecord
     */
    public ModulesRecord() {
        super(Modules.MODULES);
    }

    /**
     * Create a detached, initialised ModulesRecord
     */
    public ModulesRecord(Long id, Long packageVersionId, Long namespaceId, Timestamp createdAt, JSONB metadata) {
        super(Modules.MODULES);

        set(0, id);
        set(1, packageVersionId);
        set(2, namespaceId);
        set(3, createdAt);
        set(4, metadata);
    }
}
