/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables.records;


import eu.fasten.core.data.metadatadb.codegen.tables.Modules;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModulesRecord extends UpdatableRecordImpl<ModulesRecord> implements Record6<Long, Long, String, byte[], Timestamp, JSONB> {

    private static final long serialVersionUID = -1799281075;

    /**
     * Setter for <code>public.modules.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.modules.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.modules.package_version_id</code>.
     */
    public void setPackageVersionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.modules.package_version_id</code>.
     */
    public Long getPackageVersionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.modules.namespaces</code>.
     */
    public void setNamespaces(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.modules.namespaces</code>.
     */
    public String getNamespaces() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.modules.sha256</code>.
     */
    public void setSha256(byte... value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.modules.sha256</code>.
     */
    public byte[] getSha256() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>public.modules.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.modules.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.modules.metadata</code>.
     */
    public void setMetadata(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.modules.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, byte[], Timestamp, JSONB> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, String, byte[], Timestamp, JSONB> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Modules.MODULES.ID;
    }

    @Override
    public Field<Long> field2() {
        return Modules.MODULES.PACKAGE_VERSION_ID;
    }

    @Override
    public Field<String> field3() {
        return Modules.MODULES.NAMESPACES;
    }

    @Override
    public Field<byte[]> field4() {
        return Modules.MODULES.SHA256;
    }

    @Override
    public Field<Timestamp> field5() {
        return Modules.MODULES.CREATED_AT;
    }

    @Override
    public Field<JSONB> field6() {
        return Modules.MODULES.METADATA;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getPackageVersionId();
    }

    @Override
    public String component3() {
        return getNamespaces();
    }

    @Override
    public byte[] component4() {
        return getSha256();
    }

    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    @Override
    public JSONB component6() {
        return getMetadata();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getPackageVersionId();
    }

    @Override
    public String value3() {
        return getNamespaces();
    }

    @Override
    public byte[] value4() {
        return getSha256();
    }

    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    @Override
    public JSONB value6() {
        return getMetadata();
    }

    @Override
    public ModulesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ModulesRecord value2(Long value) {
        setPackageVersionId(value);
        return this;
    }

    @Override
    public ModulesRecord value3(String value) {
        setNamespaces(value);
        return this;
    }

    @Override
    public ModulesRecord value4(byte... value) {
        setSha256(value);
        return this;
    }

    @Override
    public ModulesRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ModulesRecord value6(JSONB value) {
        setMetadata(value);
        return this;
    }

    @Override
    public ModulesRecord values(Long value1, Long value2, String value3, byte[] value4, Timestamp value5, JSONB value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModulesRecord
     */
    public ModulesRecord() {
        super(Modules.MODULES);
    }

    /**
     * Create a detached, initialised ModulesRecord
     */
    public ModulesRecord(Long id, Long packageVersionId, String namespaces, byte[] sha256, Timestamp createdAt, JSONB metadata) {
        super(Modules.MODULES);

        set(0, id);
        set(1, packageVersionId);
        set(2, namespaces);
        set(3, sha256);
        set(4, createdAt);
        set(5, metadata);
    }
}
