/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables.records;


import eu.fasten.core.data.metadatadb.codegen.tables.Namespaces;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NamespacesRecord extends UpdatableRecordImpl<NamespacesRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 764398553;

    /**
     * Setter for <code>public.namespaces.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.namespaces.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.namespaces.namespace</code>.
     */
    public void setNamespace(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.namespaces.namespace</code>.
     */
    public String getNamespace() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Namespaces.NAMESPACES.ID;
    }

    @Override
    public Field<String> field2() {
        return Namespaces.NAMESPACES.NAMESPACE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNamespace();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNamespace();
    }

    @Override
    public NamespacesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public NamespacesRecord value2(String value) {
        setNamespace(value);
        return this;
    }

    @Override
    public NamespacesRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NamespacesRecord
     */
    public NamespacesRecord() {
        super(Namespaces.NAMESPACES);
    }

    /**
     * Create a detached, initialised NamespacesRecord
     */
    public NamespacesRecord(Long id, String namespace) {
        super(Namespaces.NAMESPACES);

        set(0, id);
        set(1, namespace);
    }
}
