/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables.records;


import eu.fasten.core.data.metadatadb.codegen.tables.VulnerabilitiesPurls;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VulnerabilitiesPurlsRecord extends TableRecordImpl<VulnerabilitiesPurlsRecord> implements Record5<Long, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vulnerabilities_purls.vulnerability_id</code>.
     */
    public void setVulnerabilityId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vulnerabilities_purls.vulnerability_id</code>.
     */
    public Long getVulnerabilityId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.vulnerabilities_purls.purl</code>.
     */
    public void setPurl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vulnerabilities_purls.purl</code>.
     */
    public String getPurl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.vulnerabilities_purls.forge</code>.
     */
    public void setForge(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vulnerabilities_purls.forge</code>.
     */
    public String getForge() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.vulnerabilities_purls.package_name</code>.
     */
    public void setPackageName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vulnerabilities_purls.package_name</code>.
     */
    public String getPackageName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.vulnerabilities_purls.package_version</code>.
     */
    public void setPackageVersion(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vulnerabilities_purls.package_version</code>.
     */
    public String getPackageVersion() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return VulnerabilitiesPurls.VULNERABILITIES_PURLS.VULNERABILITY_ID;
    }

    @Override
    public Field<String> field2() {
        return VulnerabilitiesPurls.VULNERABILITIES_PURLS.PURL;
    }

    @Override
    public Field<String> field3() {
        return VulnerabilitiesPurls.VULNERABILITIES_PURLS.FORGE;
    }

    @Override
    public Field<String> field4() {
        return VulnerabilitiesPurls.VULNERABILITIES_PURLS.PACKAGE_NAME;
    }

    @Override
    public Field<String> field5() {
        return VulnerabilitiesPurls.VULNERABILITIES_PURLS.PACKAGE_VERSION;
    }

    @Override
    public Long component1() {
        return getVulnerabilityId();
    }

    @Override
    public String component2() {
        return getPurl();
    }

    @Override
    public String component3() {
        return getForge();
    }

    @Override
    public String component4() {
        return getPackageName();
    }

    @Override
    public String component5() {
        return getPackageVersion();
    }

    @Override
    public Long value1() {
        return getVulnerabilityId();
    }

    @Override
    public String value2() {
        return getPurl();
    }

    @Override
    public String value3() {
        return getForge();
    }

    @Override
    public String value4() {
        return getPackageName();
    }

    @Override
    public String value5() {
        return getPackageVersion();
    }

    @Override
    public VulnerabilitiesPurlsRecord value1(Long value) {
        setVulnerabilityId(value);
        return this;
    }

    @Override
    public VulnerabilitiesPurlsRecord value2(String value) {
        setPurl(value);
        return this;
    }

    @Override
    public VulnerabilitiesPurlsRecord value3(String value) {
        setForge(value);
        return this;
    }

    @Override
    public VulnerabilitiesPurlsRecord value4(String value) {
        setPackageName(value);
        return this;
    }

    @Override
    public VulnerabilitiesPurlsRecord value5(String value) {
        setPackageVersion(value);
        return this;
    }

    @Override
    public VulnerabilitiesPurlsRecord values(Long value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VulnerabilitiesPurlsRecord
     */
    public VulnerabilitiesPurlsRecord() {
        super(VulnerabilitiesPurls.VULNERABILITIES_PURLS);
    }

    /**
     * Create a detached, initialised VulnerabilitiesPurlsRecord
     */
    public VulnerabilitiesPurlsRecord(Long vulnerabilityId, String purl, String forge, String packageName, String packageVersion) {
        super(VulnerabilitiesPurls.VULNERABILITIES_PURLS);

        setVulnerabilityId(vulnerabilityId);
        setPurl(purl);
        setForge(forge);
        setPackageName(packageName);
        setPackageVersion(packageVersion);
    }
}
