/*
 * This file is generated by jOOQ.
 */
package eu.fasten.core.data.metadatadb.codegen.tables.records;


import eu.fasten.core.data.metadatadb.codegen.tables.Vulnerabilities;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.15"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VulnerabilitiesRecord extends UpdatableRecordImpl<VulnerabilitiesRecord> implements Record2<String, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vulnerabilities.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vulnerabilities.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.vulnerabilities.statement</code>.
     */
    public void setStatement(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vulnerabilities.statement</code>.
     */
    public JSONB getStatement() {
        return (JSONB) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, JSONB> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, JSONB> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Vulnerabilities.VULNERABILITIES.ID;
    }

    @Override
    public Field<JSONB> field2() {
        return Vulnerabilities.VULNERABILITIES.STATEMENT;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public JSONB component2() {
        return getStatement();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public JSONB value2() {
        return getStatement();
    }

    @Override
    public VulnerabilitiesRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public VulnerabilitiesRecord value2(JSONB value) {
        setStatement(value);
        return this;
    }

    @Override
    public VulnerabilitiesRecord values(String value1, JSONB value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VulnerabilitiesRecord
     */
    public VulnerabilitiesRecord() {
        super(Vulnerabilities.VULNERABILITIES);
    }

    /**
     * Create a detached, initialised VulnerabilitiesRecord
     */
    public VulnerabilitiesRecord(String id, JSONB statement) {
        super(Vulnerabilities.VULNERABILITIES);

        setId(id);
        setStatement(statement);
    }
}
